services:
  edrixs-jupyter:
    image: mpmdean/edrixs_petsc
    volumes:
      - ./:/home/rixs
    working_dir: /home/rixs
    platform: linux/arm64
    ports:
      - "8888:8888"
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  edrixs-ipython:
    image: mpmdean/edrixs_petsc
    volumes:
      - ./:/home/rixs
    working_dir: /home/rixs
    platform: linux/arm64
